# Generated by Django 4.2 on 2023-05-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='services',
            name='descr',
            field=models.TextField(verbose_name='Описание услуги  '),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название услуги'),
        ),
    ]
